import { SHADER_ATTR, SHADER_UNIFORM, SHADER_IN_OUT } from "./types";

// prettier-ignore
export const VERTEX_SHADER = `
#version 300 es

in vec3 ${SHADER_ATTR.POSITION};
in vec2 ${SHADER_ATTR.TEX_COORD};
in vec2 ${SHADER_ATTR.TEX_OFFSET};

uniform mat4 ${SHADER_UNIFORM.MVP_MATRIX};
uniform vec2 ${SHADER_UNIFORM.TEX_INFO};

out vec3 ${SHADER_IN_OUT.POSITION};
out vec2 ${SHADER_IN_OUT.TEX_COORD};
out vec2 ${SHADER_IN_OUT.TEX_OFFSET};
out vec2 ${SHADER_IN_OUT.TEX_INFO};

void main(void) {  
  ${SHADER_IN_OUT.POSITION} = ${SHADER_ATTR.POSITION};
  ${SHADER_IN_OUT.TEX_COORD} = ${SHADER_ATTR.TEX_COORD};
  ${SHADER_IN_OUT.TEX_OFFSET} = ${SHADER_ATTR.TEX_OFFSET};
  ${SHADER_IN_OUT.TEX_INFO} = ${SHADER_UNIFORM.TEX_INFO};

  gl_Position = ${SHADER_UNIFORM.MVP_MATRIX} * vec4(${SHADER_ATTR.POSITION}, 1.0);
}
`.trim();
