export enum TEXTURE {
  ATLAS = "ATLAS"
}

export enum ATLAS {
  COBBLESTONE = "COBBLESTONE",
  GRASS = "GRASS",
  STONE = "STONE",
  DIRT = "DIRT",
  DIRT_WITH_GRASS = "DIRT_WITH_GRASS",
  WOOD_0 = "WOOD_0",
  BEDROCK = "BEDROCK",
  SAND = "SAND",
  GRAVEL = "GRAVEL",
  WOOD = "WOOD",
  GOLD_ORE = "GOLD_ORE",
  IRON_ORE = "IRON_ORE",
  COAL_ORE = "COAL_ORE",
  BOOKSHELF = "BOOKSHELF",
  MOSS_STONE = "MOSS_STONE",
  SPONGE = "SPONGE",
  GLASS = "GLASS",
  DIAMOND_ORE = "DIAMOND_ORE",
  REDSTONE_ORE = "REDSTONE_ORE",
  LEAVES = "LEAVES",
  WOOL = "WOOL",
  MONSTER_SPAWNER = "MONSTER_SPAWNER",
  SNOW = "snSNOWow",
  ICE = "ICE",
  DIRT_WITH_SNOW = "DIRT_WITH_SNOW"
}

export enum TEXTURE_SRC {
  ATLAS = "./assets/atlas.png"
}

export const ATLAS_SIZE = 80;
export const CROP_SIZE = 16;

export const GL_PIXEL_SIZE = 1.0 / ATLAS_SIZE;
export const GL_CROP_SIZE = GL_PIXEL_SIZE * CROP_SIZE;
